### ISSUE TITLE
(feature request) include example oauth file, but prevent that from being git commited

### ISSUE THREAD

**Issue by drandreaskrueger** [geduldig/TwitterGeoPics#5]
Have a look:

* .[gitignore](https://github.com/drandreaskrueger/TwitterGeoPics/blob/6228cb2a9b1898342d712cbb59251fccd921faa1/.gitignore#L41)
* [twitterapi-oauth.txt](https://github.com/drandreaskrueger/TwitterGeoPics/blob/6228cb2a9b1898342d712cbb59251fccd921faa1/twitterapi-oauth.txt)

how to (a) include that file as an example into the repo, but (b) prevent it from showing up at `git status` when the content is overwritten with my personal credentials - which of course I do not want to `git add .; git commit ...` 

There must be some git trick for that, but I don't know.

**Comment by geduldig** [comment]
Store your credentials in `TwitterAPI/credentials.txt`, and they will get read by `TwitterOAuth.read_file()` with no arguments.
